#!/usr/bin/env node
/*
 * server.js — admin backend for the /now page.
 *
 * The static terminal site (index.html) enters "admin mode" with Cmd/Ctrl+E and
 * posts here to compose & publish NOW.txt. On every write this server:
 *   1. mutates files under ./root (archiving the old NOW.txt into ./root/home/marcus/NOW/)
 *   2. runs `node server/build.js` to regenerate root/manifest.json + root/fs.js
 *   3. git add / commit / push   (so GitHub Pages redeploys)
 *
 * Run:
 *   node server/server.js         (from the project root)
 *
 * Env vars (all optional):
 *   PORT=8787            port to listen on
 *   ADMIN_TOKEN=secret   if set, mutating requests must send  X-Admin-Token: secret
 *   ALLOW_ORIGIN=*       CORS origin to allow (default *)
 *   GIT_BRANCH=main      branch to push (default: current branch)
 *   GIT_REMOTE=origin    remote to push to (default origin)
 *   NO_GIT=1             skip the git commit/push step (handy for local testing)
 *   NO_DEPLOY=1          skip the post-push deploy hook (update-production.sh)
 *   NO_BUILD=1           skip running build.js
 *
 * No npm dependencies — Node standard library only.
 *
 * API (JSON in, JSON out):
 *   GET  /api/health              -> { ok, version }
 *   GET  /api/now                 -> { date, content, raw }
 *   PUT  /api/now                 -> overwrite NOW.txt in place        body { date, content }
 *   POST /api/now                 -> publish: archive current -> NOW/, body { date, content }
 *                                    then write the new NOW.txt
 *   GET  /api/was                 -> { items: [ { name, date, raw } ] }
 *   PUT  /api/was?name=….-NOW.txt -> overwrite an archived file        body { date, content }
 *   GET  /api/readme              -> { raw }
 *   PUT  /api/readme              -> overwrite README.txt in place     body { content }
 *   GET  /api/files               -> { items: [ { path, size } ] }  (all editable files under ./root)
 *   GET  /api/file?path=rel       -> { path, raw }
 *   PUT  /api/file                -> create/overwrite a file          body { path, content }
 *   DELETE /api/file?path=rel     -> delete a file
 *
 *   ./root/manifest.json and ./root/fs.js are generated by build.js and are never editable.
 */

'use strict';

const http = require('http');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');   // project root (server.js lives in ./server)
const MARCUS_DIR = path.join(ROOT, 'root', 'home', 'marcus');
const NOW_FILE = path.join(MARCUS_DIR, 'NOW.txt');
const README_FILE = path.join(MARCUS_DIR, 'README.txt');
const ROOT_DIR = path.join(ROOT, 'root');            // everything the terminal serves
const BLOCKED = new Set(['manifest.json', 'fs.js']); // generated by build.js — never hand-edit

// Resolve a caller-supplied path against ./root, refusing escapes and generated files.
function safePath(rel) {
  const clean = String(rel == null ? '' : rel).replace(/\\/g, '/').replace(/^\/+/, '');
  if (!clean) throw new Error('path required');
  const full = path.resolve(ROOT_DIR, clean);
  const within = path.relative(ROOT_DIR, full);
  if (within === '' || within.startsWith('..') || path.isAbsolute(within)) throw new Error('path escapes ./root');
  if (BLOCKED.has(path.basename(full))) throw new Error(path.basename(full) + ' is generated by build.js — not editable');
  if (within.split(path.sep).indexOf('.git') !== -1) throw new Error('.git is not editable');
  return { full: full, rel: within.split(path.sep).join('/') };
}

// Walk ./root and return editable files + every directory (incl. empty ones).
// dotfiles included; manifest.json/fs.js/.git excluded.
function listTree() {
  const files = [], dirs = [];
  (function walk(dir, rel) {
    let names;
    try { names = fs.readdirSync(dir).sort((a, b) => a.localeCompare(b)); } catch (e) { return; }
    for (const name of names) {
      if (name === '.git') continue;
      const full = path.join(dir, name);
      const r = rel ? rel + '/' + name : name;
      let st; try { st = fs.statSync(full); } catch (e) { continue; }
      if (st.isDirectory()) { dirs.push(r); walk(full, r); }
      else if (!BLOCKED.has(name)) files.push({ path: r, size: st.size });
    }
  })(ROOT_DIR, '');
  return { files: files, dirs: dirs };
}
function listFiles() { return listTree().files; }
const NOW_DIR = path.join(MARCUS_DIR, 'NOW');   // archive of past NOW.txt entries
const BUILD_JS = path.join(__dirname, 'build.js');   // build.js sits next to this file in ./server
const DEPLOY_SH = path.join(__dirname, 'update-production.sh');   // ssh to the web box + git pull

const PORT = parseInt(process.env.PORT || '8787', 10);
const TOKEN = process.env.ADMIN_TOKEN || '';
const ALLOW_ORIGIN = process.env.ALLOW_ORIGIN || '*';
const GIT_BRANCH = process.env.GIT_BRANCH || '';
const GIT_REMOTE = process.env.GIT_REMOTE || 'origin';
const NO_GIT = process.env.NO_GIT === '1';
const NO_BUILD = process.env.NO_BUILD === '1';
const NO_DEPLOY = process.env.NO_DEPLOY === '1';
const VERSION = 'now-admin/1.0';

const NOW_FOOTER = 'more: cat README.txt';
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'];

// ---------- helpers ----------

function todayLabel() {
  const d = new Date();
  return MONTHS[d.getMonth()] + ' ' + d.getDate() + ', ' + d.getFullYear();
}

// Assemble the canonical NOW.txt text. When there is a most-recent archived entry,
// append a hint showing how to read past entries.
function buildNowText(date, content, archiveHint) {
  const body = String(content == null ? '' : content).replace(/\r/g, '').replace(/\s+$/, '');
  let footer = '';
  if (archiveHint) footer += 'to see what I was doing:\n  ls NOW\n  cat NOW/' + archiveHint + '\n\n';
  footer += NOW_FOOTER;
  return 'last updated: ' + String(date).trim() + '\n\n' + body + '\n\n' + footer + '\n';
}

// "July 1, 2026"  ->  "2026-07-01"   (accepts a full "last updated: …" line too)
function toISODate(input) {
  const m = /last updated:\s*(.+)/i.exec(input);
  const raw = (m ? m[1] : String(input)).trim();
  const d = new Date(raw);
  if (isNaN(d.getTime())) return null;
  const p = (n) => String(n).padStart(2, '0');
  return d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate());
}

// Derive the archive date for an existing NOW.txt: first line, else file mtime, else today.
function archiveDateFor(rawText, filePath) {
  const firstLine = String(rawText).split('\n')[0] || '';
  let iso = toISODate(firstLine);
  if (iso) return iso;
  try {
    const d = fs.statSync(filePath).mtime;
    const p = (n) => String(n).padStart(2, '0');
    iso = d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate());
  } catch (e) { /* ignore */ }
  return iso || toISODate(todayLabel());
}

function ensureDir(dir) { if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true }); }

// Pick an unused NOW/ archive filename for a given ISO date (avoids clobbering same-day archives).
function uniqueArchivePath(iso) {
  ensureDir(NOW_DIR);
  let name = iso + '-NOW.txt';
  let full = path.join(NOW_DIR, name);
  let i = 2;
  while (fs.existsSync(full)) { name = iso + '-' + i + '-NOW.txt'; full = path.join(NOW_DIR, name); i++; }
  return { name: name, full: full };
}

// Filename of the most-recently-dated archived entry, or null.
function latestArchiveName() {
  const items = listWas();
  return items.length ? items[0].name : null;
}

function run(cmd, args) {
  return execFileSync(cmd, args, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
}

function runBuild() {
  if (NO_BUILD) return 'build skipped';
  try {
    // Regenerate root/manifest.json + root/fs.js from the (just-mutated) ./root tree.
    const out = run(process.execPath, [BUILD_JS]);   // same node binary that runs this server (nvm-safe under systemd)
    const m = /\((\d+) files embedded\)/.exec(out);
    return m ? ('built · ' + m[1] + ' files' ) : 'built';
  } catch (e) {
    const detail = (e.stderr || e.stdout || e.message || '').toString().trim().split('\n').slice(-2).join(' ');
    throw new Error('build.js failed: ' + detail);
  }
}

// After a successful push, tell the production web box to pull the new commit.
// Never throws — a deploy failure shouldn't undo the (already-pushed) commit.
function runDeploy() {
  if (NO_DEPLOY) return 'deploy skipped';
  if (!fs.existsSync(DEPLOY_SH)) return 'deploy script missing';
  try {
    run('bash', [DEPLOY_SH]);
    return 'deployed';
  } catch (e) {
    const detail = (e.stderr || e.stdout || e.message || '').toString().trim().split('\n').slice(-2).join(' ');
    return 'deploy hook failed: ' + detail;
  }
}

// git add -A ; commit ; push. Returns a short human summary; never throws.
function gitPublish(message) {
  if (NO_GIT) return 'git skipped';
  try {
    run('git', ['add', '-A']);
    // nothing staged? bail cleanly
    try { run('git', ['diff', '--cached', '--quiet']); return 'no changes to commit'; } catch (e) { /* there ARE changes */ }
    run('git', ['commit', '-m', message]);
    const branch = GIT_BRANCH || run('git', ['rev-parse', '--abbrev-ref', 'HEAD']);
    run('git', ['push', GIT_REMOTE, branch]);
    // push succeeded — trigger the production deploy (ssh + git pull on the web box)
    const deploy = runDeploy();
    return 'committed & pushed to ' + GIT_REMOTE + '/' + branch + (deploy ? ' · ' + deploy : '');
  } catch (e) {
    const detail = (e.stderr || e.stdout || e.message || '').toString().trim().split('\n').slice(-2).join(' ');
    return 'git error: ' + detail;
  }
}

function readNow() {
  if (!fs.existsSync(NOW_FILE)) return null;
  return fs.readFileSync(NOW_FILE, 'utf8');
}

// A trailing footer line the editable content should never include.
function isFooterLine(l) {
  return l.trim() === '' || /^more:\s*cat\s+README\.txt/i.test(l) ||
    /^to see what i was doing/i.test(l) || /^\s*ls\s+NOW\s*$/i.test(l) || /^\s*cat\s+NOW\//i.test(l);
}
function parseNow(raw) {
  const lines = String(raw == null ? '' : raw).replace(/\r/g, '').split('\n');
  const m = /last updated:\s*(.+)/i.exec(lines[0] || '');
  let body = lines.slice(m ? 1 : 0);
  while (body.length && body[0].trim() === '') body.shift();
  while (body.length && isFooterLine(body[body.length - 1])) body.pop();
  return { date: (m ? m[1].trim() : '') || todayLabel(), content: body.join('\n'), raw: raw };
}

function listWas() {
  if (!fs.existsSync(NOW_DIR)) return [];
  return fs.readdirSync(NOW_DIR)
    .filter((f) => /-NOW\.txt$/.test(f))
    .sort((a, b) => b.localeCompare(a))
    .map((name) => {
      const raw = fs.readFileSync(path.join(NOW_DIR, name), 'utf8');
      return { name: name, date: parseNow(raw).date, raw: raw };
    });
}

// ---------- request handling ----------

function send(res, code, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(code, {
    'Content-Type': 'application/json; charset=utf-8',
    'Access-Control-Allow-Origin': ALLOW_ORIGIN,
    'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, X-Admin-Token',
    'Cache-Control': 'no-store'
  });
  res.end(body);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', (c) => { data += c; if (data.length > 1e6) { reject(new Error('body too large')); req.destroy(); } });
    req.on('end', () => { if (!data) return resolve({}); try { resolve(JSON.parse(data)); } catch (e) { reject(new Error('invalid JSON body')); } });
    req.on('error', reject);
  });
}

function authed(req) { return !TOKEN || req.headers['x-admin-token'] === TOKEN; }

const server = http.createServer(async (req, res) => {
  const u = new URL(req.url, 'http://localhost');
  const p = u.pathname.replace(/\/+$/, '') || '/';
  const method = req.method.toUpperCase();

  if (method === 'OPTIONS') { send(res, 204, {}); return; }

  try {
    if ((p === '/' || p === '/api') && method === 'GET') {
      return send(res, 200, {
        ok: true,
        service: VERSION,
        message: 'now-admin backend is running. Point the admin panel (Cmd/Ctrl+E on the site) at this URL.',
        routes: [
          'GET /api/health', 'GET /api/now', 'PUT /api/now', 'POST /api/now',
          'GET /api/was', 'PUT /api/was?name=', 'GET /api/readme', 'PUT /api/readme',
          'GET /api/files', 'GET /api/file?path=', 'PUT /api/file', 'DELETE /api/file?path='
        ]
      });
    }

    if (p === '/api/health' && method === 'GET') {
      return send(res, 200, { ok: true, version: VERSION, git: !NO_GIT, build: !NO_BUILD });
    }

    if (p === '/api/now' && method === 'GET') {
      const raw = readNow();
      if (raw == null) return send(res, 404, { error: 'NOW.txt not found' });
      return send(res, 200, parseNow(raw));
    }

    if (p === '/api/was' && method === 'GET') {
      return send(res, 200, { items: listWas() });
    }

    if (p === '/api/readme' && method === 'GET') {
      if (!fs.existsSync(README_FILE)) return send(res, 404, { error: 'README.txt not found' });
      return send(res, 200, { raw: fs.readFileSync(README_FILE, 'utf8') });
    }

    if (p === '/api/files' && method === 'GET') {
      const t = listTree();
      return send(res, 200, { items: t.files, dirs: t.dirs });
    }

    if (p === '/api/file' && method === 'GET') {
      const sp = safePath(u.searchParams.get('path'));
      if (!fs.existsSync(sp.full) || fs.statSync(sp.full).isDirectory()) return send(res, 404, { error: 'not found: ' + sp.rel });
      return send(res, 200, { path: sp.rel, raw: fs.readFileSync(sp.full, 'utf8') });
    }

    // ---- mutations below require auth ----
    if (!authed(req)) return send(res, 401, { error: 'unauthorized (bad or missing X-Admin-Token)' });

    if (p === '/api/now' && method === 'POST') {
      // PUBLISH: archive the current NOW.txt, then write the new one.
      const body = await readBody(req);
      const date = String(body.date || todayLabel()).trim();
      let archived = null;
      const current = readNow();
      if (current != null && current.trim() !== '') {
        const iso = archiveDateFor(current, NOW_FILE);
        const dest = uniqueArchivePath(iso);
        fs.writeFileSync(dest.full, current, 'utf8');
        archived = 'NOW/' + dest.name;
      }
      fs.writeFileSync(NOW_FILE, buildNowText(date, body.content, latestArchiveName()), 'utf8');
      const built = runBuild();
      const git = gitPublish('now: publish ' + date + (archived ? ' (archived ' + archived + ')' : ''));
      return send(res, 200, { ok: true, archived: archived, built: built, git: git, now: parseNow(readNow()) });
    }

    if (p === '/api/now' && method === 'PUT') {
      // EDIT in place — no archive.
      const body = await readBody(req);
      const date = String(body.date || todayLabel()).trim();
      fs.writeFileSync(NOW_FILE, buildNowText(date, body.content, latestArchiveName()), 'utf8');
      const built = runBuild();
      const git = gitPublish('now: edit ' + date);
      return send(res, 200, { ok: true, built: built, git: git, now: parseNow(readNow()) });
    }

    if (p === '/api/was' && method === 'PUT') {
      const name = u.searchParams.get('name') || '';
      if (!/-NOW\.txt$/.test(name) || /[\/\\]/.test(name)) return send(res, 400, { error: 'bad archive name' });
      const full = path.join(NOW_DIR, name);
      if (!fs.existsSync(full)) return send(res, 404, { error: 'archive not found: ' + name });
      const body = await readBody(req);
      const date = String(body.date || parseNow(fs.readFileSync(full, 'utf8')).date).trim();
      fs.writeFileSync(full, buildNowText(date, body.content), 'utf8');
      const built = runBuild();
      const git = gitPublish('now: edit archive ' + name);
      return send(res, 200, { ok: true, built: built, git: git });
    }

    if (p === '/api/readme' && method === 'PUT') {
      // EDIT README.txt in place — freeform text, no date/footer wrapping.
      const body = await readBody(req);
      let text = String(body.content == null ? '' : body.content).replace(/\r/g, '');
      if (!/\n$/.test(text)) text += '\n';
      fs.writeFileSync(README_FILE, text, 'utf8');
      const built = runBuild();
      const git = gitPublish('now: edit README.txt');
      return send(res, 200, { ok: true, built: built, git: git });
    }

    if (p === '/api/file' && (method === 'PUT' || method === 'POST')) {
      // Create or overwrite any file under ./root (dotfiles & nested dirs ok).
      const body = await readBody(req);
      const target = safePath(body.path != null ? body.path : u.searchParams.get('path'));
      fs.mkdirSync(path.dirname(target.full), { recursive: true });
      const existed = fs.existsSync(target.full);
      fs.writeFileSync(target.full, String(body.content == null ? '' : body.content), 'utf8');
      const built = runBuild();
      const git = gitPublish('now: ' + (existed ? 'edit' : 'create') + ' ' + target.rel);
      return send(res, 200, { ok: true, path: target.rel, created: !existed, built: built, git: git });
    }

    if (p === '/api/file' && method === 'DELETE') {
      const target = safePath(u.searchParams.get('path'));
      if (!fs.existsSync(target.full)) return send(res, 404, { error: 'not found: ' + target.rel });
      if (fs.statSync(target.full).isDirectory()) fs.rmSync(target.full, { recursive: true });
      else fs.unlinkSync(target.full);
      const built = runBuild();
      const git = gitPublish('now: delete ' + target.rel);
      return send(res, 200, { ok: true, path: target.rel, built: built, git: git });
    }

    return send(res, 404, { error: 'no such route: ' + method + ' ' + p });
  } catch (err) {
    return send(res, 500, { error: (err && err.message) || 'server error' });
  }
});

server.listen(PORT, () => {
  console.log('now-admin server.js listening on http://localhost:' + PORT);
  console.log('  root:      ' + ROOT);
  console.log('  NOW.txt:   ' + path.relative(ROOT, NOW_FILE));
  console.log('  archive:   ' + path.relative(ROOT, NOW_DIR) + '/');
  console.log('  auth:      ' + (TOKEN ? 'X-Admin-Token required' : 'OPEN (set ADMIN_TOKEN to lock down)'));
  console.log('  git push:  ' + (NO_GIT ? 'disabled (NO_GIT=1)' : 'enabled'));
  console.log('  deploy:    ' + (NO_DEPLOY ? 'disabled (NO_DEPLOY=1)' : 'update-production.sh after push'));
  console.log('  build.js:  ' + (NO_BUILD ? 'disabled (NO_BUILD=1)' : 'enabled'));
});
